/**
 * Spring Boot AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Response object for item details
 */
export interface ItemResponse { 
    /**
     * Unique identifier of the item
     */
    id?: number;
    /**
     * Name of the item
     */
    name?: string;
    /**
     * Description of the item
     */
    description?: string;
    /**
     * Creation timestamp
     */
    createdAt?: string;
}

