/**
 * Spring Boot AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Response object for login operation
 */
export interface LoginResponse { 
    /**
     * Indicates if login was successful
     */
    success?: boolean;
    /**
     * Message describing the result
     */
    message?: string;
    /**
     * Username of the logged-in user
     */
    username?: string;
    /**
     * JWT token for authentication
     */
    token?: string;
}

