/**
 * Spring Boot AI API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Request object for user login
 */
export interface LoginRequest { 
    /**
     * Username for authentication
     */
    username: string;
    /**
     * Password for authentication
     */
    password: string;
}

